import { useEffect, useState } from "react";
import * as XLSX from "xlsx";
import { Loader2, AlertCircle, FileSpreadsheet } from "lucide-react";

/**
 * Excel Viewer using SheetJS (xlsx)
 * Renders Excel content as a styled HTML table with tab navigation.
 */
interface ExcelViewerProps {
  url: string;
  className?: string;
}

const ExcelViewer = ({ url, className = "" }: ExcelViewerProps) => {
  const [workbook, setWorkbook] = useState<XLSX.WorkBook | null>(null);
  const [activeSheet, setActiveSheet] = useState("");
  const [htmlContent, setHtmlContent] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    let active = true;

    const fetchAndParseExcel = async () => {
      try {
        setLoading(true);
        setError(null);

        const response = await fetch(url);
        if (!response.ok) throw new Error("Không thể tải file Excel");

        const arrayBuffer = await response.arrayBuffer();

        if (!active) return; // Prevent race conditions

        // Parse Workbook
        const wb = XLSX.read(arrayBuffer, { type: "array" });
        setWorkbook(wb);

        // Default to first sheet
        if (wb.SheetNames.length > 0) {
          const firstSheet = wb.SheetNames[0];
          setActiveSheet(firstSheet);
          renderSheet(wb, firstSheet);
        }
      } catch (err) {
        console.error("Excel parse error:", err);
        if (active) setError("Lỗi khi đọc file Excel.");
      } finally {
        if (active) setLoading(false);
      }
    };

    if (url) fetchAndParseExcel();

    return () => {
      active = false;
    };
  }, [url]);

  // Handle switching tabs
  const handleSheetChange = (sheetName: string) => {
    setActiveSheet(sheetName);
    if (workbook) {
      renderSheet(workbook, sheetName);
    }
  };

  // Convert Sheet to HTML Table
  const renderSheet = (wb: XLSX.WorkBook, sheetName: string) => {
    const ws = wb.Sheets[sheetName];
    // sheet_to_html produces a simple HTML table string
    const html = XLSX.utils.sheet_to_html(ws, {
      id: "excel-table",
      editable: false,
    });
    setHtmlContent(html);
  };

  return (
    <div
      className={`flex flex-col h-[70vh] bg-white border border-gray-300 rounded-lg overflow-hidden ${className}`}
    >
      {/* Header / Loading / Error */}
      {(loading || error) && (
        <div className="flex-1 flex items-center justify-center p-10">
          {loading ? (
            <div className="flex flex-col items-center gap-2">
              <Loader2 className="animate-spin text-green-600" size={32} />
              <span className="text-gray-500 text-sm">
                Đang xử lý file Excel...
              </span>
            </div>
          ) : (
            <div className="text-center">
              <AlertCircle className="mx-auto text-red-500 mb-2" size={32} />
              <p className="text-gray-700">{error}</p>
              <a
                href={url}
                download
                className="text-blue-600 hover:underline mt-2 inline-block"
              >
                Tải xuống để xem
              </a>
            </div>
          )}
        </div>
      )}

      {!loading && !error && workbook && (
        <>
          {/* Main Content Area - Scrollable */}
          <div className="flex-1 overflow-auto bg-gray-50 p-4 relative custom-excel-scroll">
            {/* 
              Inject HTML safely. 
              The HTML generated by XLSX is just a table structure, relatively safe.
            */}
            <div
              className="excel-preview-container bg-white shadow-sm inline-block min-w-full"
              dangerouslySetInnerHTML={{ __html: htmlContent }}
            />
          </div>

          {/* Footer - Sheet Tabs */}
          <div className="flex items-center gap-1 bg-gray-100 border-t border-gray-300 p-1 overflow-x-auto">
            <div className="px-3 py-2 text-green-700">
              <FileSpreadsheet size={18} />
            </div>
            {workbook.SheetNames.map((sheet) => (
              <button
                key={sheet}
                onClick={() => handleSheetChange(sheet)}
                className={`
                   px-4 py-1.5 text-sm whitespace-nowrap rounded-t-lg transition-colors border-b-2
                   ${
                     activeSheet === sheet
                       ? "bg-white text-green-700 font-medium border-green-600 shadow-sm"
                       : "text-gray-600 hover:bg-gray-200 border-transparent"
                   }
                 `}
              >
                {sheet}
              </button>
            ))}
          </div>
        </>
      )}

      {/* Internal CSS for Table Styling */}
      <style>{`
        .excel-preview-container table {
          border-collapse: collapse;
          width: 100%;
          font-family: Arial, sans-serif;
          font-size: 14px;
        }
        .excel-preview-container td,
        .excel-preview-container th {
          border: 1px solid #e0e0e0;
          padding: 6px 10px;
          white-space: nowrap;
          color: #333;
        }
        /* Simulate Header Row styles if detected (usually first row) */
        .excel-preview-container tr:first-child td {
          background-color: #f8f9fa;
          font-weight: bold;
          text-align: center;
          color: #444;
          border-bottom: 2px solid #ddd;
        }
        /* Alternating rows for readability */
        .excel-preview-container tr:nth-child(even) {
          background-color: #fafafa;
        }
        .excel-preview-container tr:hover td {
          background-color: #e8f5e9; /* Light green hover */
        }
      `}</style>
    </div>
  );
};

export default ExcelViewer;
